CC=mpicc

all: chang_roberts hello_mpi hello_neighbor hello_master

chang_roberts:
	$(CC) -o chang_roberts chang_roberts.c

hello_mpi:
	$(CC) -o hello_mpi hello_mpi.c

hello_neighbor:
	$(CC) -o hello_neighbor hello_neighbor.c

hello master:
	$(CC) -o hello_master hello_master.c

clean:
	rm -f chang_roberts hello_mpi hello_neighbor hello_master
